name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage", "crash", "freeze", "memory leak", "performance", "optimization needed", "loading issue", "rendering issue", "lighting issue"]
projects: ["Bestellwesen-Kurszentrum"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for bravely venturing into the depths of bug reporting! We salute your sacrifice.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we summon you if we need more intel?
      placeholder: ex. carrier.pigeon@castle.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Describe the chaos!
      value: "Something went horribly, hilariously wrong!"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.0
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Safari
        - Internet Explorer
        - Tor
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Submission Acknowledgment
      description: You acknowledge that JIRA is usually used for issue tracking, but today we don't care. We are using GitHub.
      options:
        - label: I acknowledge that JIRA is the usual platform, but we are using GitHub today
          required: true

